### ISSUE TITLE
Documentation required to make example work

### ISSUE THREAD

**Issue by sathishvj** [bunsenapp/go-selenium#1]
I installed the library and then did a `go run main.go` in the examples/gettingstarted folder.  But it gave an error: `CreateSession: api error, url: http://localhost:4444/wd/hub/session, err: &{Message: State:}`

Could you please provide more documentation on how to get started?  Are any other installs necessary?

**Comment by heraclmene** [comment]
Thanks for the feedback! I'll try and get this added to the repository some time today, although I do have a lot going on with family due to it being new years!

This library is essentially a client for the Selenium remote driver application. In order to use it, you will need a running Selenium server. There are a few ways of doing this, my preferred way is to use Docker (https://github.com/SeleniumHQ/docker-selenium) but you can also download the standalone java file, include the appropriate drivers on your path (for Firefox: Gecko, for Chrome: ChromeDriver) and run it that way. I've included a few simple steps on how to do both below:

**Without Docker**

1. Download the Selenium standalone server from here: http://www.seleniumhq.org/download/
2. Download the appropriate driver executable and include it on your path. For Firefox, that will be the Gecko driver (located here: https://github.com/mozilla/geckodriver).
3. Run the Selenium server with the following command: `java -jar selenium-server-standalone-3.0.1.jar`
4. Run the examples again.

**With Docker**
1. Execute the following Docker command: `docker run -d -p4444:4444 --name selenium selenium/standalone-firefox`
2. Run the examples again.

Let me know if you need any further help - and hope you have had a wonderful new year! 

p.s. I'll close this issue once I have committed the documentation changes.

**Comment by flavio022** [comment]
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.27/containers/create?name=selenium: dial unix /var/run/docker.sock: connect: permission denied
